<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ItemsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('items')->truncate();
        DB::statement('ALTER SEQUENCE items_item_id_seq RESTART WITH 1;');

        DB::table('items')->insert([
            [ 'item_name' => 'KIDS Sneakers Yellow Casual and Formal Cotton and Wool', 'price' => 47.27, 'description' => 'KIDS Sneakers Yellow Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 1, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Yellow', 'times_bought' => 28, 'release_date' => '2025-02-23' ],
            [ 'item_name' => 'MEN Boots Black Casual and Formal Cotton and Polyester', 'price' => 36.69, 'description' => 'MEN Boots Black Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 2, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Black', 'times_bought' => 38, 'release_date' => '2025-04-09' ],
            [ 'item_name' => 'WOMEN Sports shoes Black Casual and Formal Wool and Polyester', 'price' => 57.09, 'description' => 'WOMEN Sports shoes Black Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 3, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Black', 'times_bought' => 34, 'release_date' => '2025-03-21' ],
            [ 'item_name' => 'KIDS Open shoes Blue Casual and Cozy Cotton and Wool', 'price' => 43.95, 'description' => 'KIDS Open shoes Blue Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 4, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Blue', 'times_bought' => 7, 'release_date' => '2025-04-19' ],
            [ 'item_name' => 'MEN Exclusive Yellow Casual and Cozy Cotton and Polyester', 'price' => 20.33, 'description' => 'MEN Exclusive Yellow Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 5, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Yellow', 'times_bought' => 32, 'release_date' => '2025-04-03' ],
            [ 'item_name' => 'WOMEN Long sleeved Red Casual and Cozy Wool and Polyester', 'price' => 38.34, 'description' => 'WOMEN Long sleeved Red Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 6, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Red', 'times_bought' => 2, 'release_date' => '2025-03-23' ],
            [ 'item_name' => 'KIDS Short sleeved White Formal and Cozy Cotton and Wool', 'price' => 44.03, 'description' => 'KIDS Short sleeved White Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 7, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'White', 'times_bought' => 38, 'release_date' => '2025-02-23' ],
            [ 'item_name' => 'MEN Tank tops White Formal and Cozy Cotton and Polyester', 'price' => 52.2, 'description' => 'MEN Tank tops White Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 8, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'White', 'times_bought' => 43, 'release_date' => '2025-02-02' ],
            [ 'item_name' => 'WOMEN Polo shirts Black Formal and Cozy Wool and Polyester', 'price' => 40.11, 'description' => 'WOMEN Polo shirts Black Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 9, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'Black', 'times_bought' => 35, 'release_date' => '2025-03-30' ],
            [ 'item_name' => 'KIDS Sport Black Casual and Formal Cotton and Wool', 'price' => 29.05, 'description' => 'KIDS Sport Black Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 10, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Black', 'times_bought' => 6, 'release_date' => '2025-03-17' ],
            [ 'item_name' => 'MEN Jeans Blue Casual and Formal Cotton and Polyester', 'price' => 19.28, 'description' => 'MEN Jeans Blue Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 11, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Blue', 'times_bought' => 28, 'release_date' => '2025-03-02' ],
            [ 'item_name' => 'WOMEN Shorts Green Casual and Formal Wool and Polyester', 'price' => 45.51, 'description' => 'WOMEN Shorts Green Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 12, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Green', 'times_bought' => 26, 'release_date' => '2025-02-10' ],
            [ 'item_name' => 'KIDS Cargo pants Green Casual and Cozy Cotton and Wool', 'price' => 67.91, 'description' => 'KIDS Cargo pants Green Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 13, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Green', 'times_bought' => 4, 'release_date' => '2025-02-18' ],
            [ 'item_name' => 'MEN Tracksuit pants Yellow Casual and Cozy Cotton and Polyester', 'price' => 67.8, 'description' => 'MEN Tracksuit pants Yellow Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 14, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Yellow', 'times_bought' => 9, 'release_date' => '2025-04-28' ],
            [ 'item_name' => 'WOMEN Fabric pants Blue Casual and Cozy Wool and Polyester', 'price' => 25.98, 'description' => 'WOMEN Fabric pants Blue Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 15, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Blue', 'times_bought' => 34, 'release_date' => '2025-04-20' ],
            [ 'item_name' => 'KIDS Other Blue Formal and Cozy Cotton and Wool', 'price' => 43.92, 'description' => 'KIDS Other Blue Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 16, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'Blue', 'times_bought' => 33, 'release_date' => '2025-03-18' ],
            [ 'item_name' => 'MEN Sneakers Blue Formal and Cozy Cotton and Polyester', 'price' => 68.86, 'description' => 'MEN Sneakers Blue Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 1, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Blue', 'times_bought' => 9, 'release_date' => '2025-04-16' ],
            [ 'item_name' => 'WOMEN Boots Yellow Formal and Cozy Wool and Polyester', 'price' => 29.38, 'description' => 'WOMEN Boots Yellow Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 2, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'Yellow', 'times_bought' => 4, 'release_date' => '2025-03-07' ],
            [ 'item_name' => 'KIDS Sports shoes Green Casual and Formal Cotton and Wool', 'price' => 63.22, 'description' => 'KIDS Sports shoes Green Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 3, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Green', 'times_bought' => 12, 'release_date' => '2025-02-06' ],
            [ 'item_name' => 'MEN Open shoes Black Casual and Formal Cotton and Polyester', 'price' => 48.04, 'description' => 'MEN Open shoes Black Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 4, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Black', 'times_bought' => 30, 'release_date' => '2025-04-30' ],
            [ 'item_name' => 'WOMEN Exclusive Black Casual and Formal Wool and Polyester', 'price' => 56.78, 'description' => 'WOMEN Exclusive Black Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 5, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Black', 'times_bought' => 44, 'release_date' => '2025-03-15' ],
            [ 'item_name' => 'KIDS Long sleeved Blue Casual and Cozy Cotton and Wool', 'price' => 16.76, 'description' => 'KIDS Long sleeved Blue Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 6, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Blue', 'times_bought' => 7, 'release_date' => '2025-04-02' ],
            [ 'item_name' => 'MEN Short sleeved Blue Casual and Cozy Cotton and Polyester', 'price' => 19.1, 'description' => 'MEN Short sleeved Blue Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 7, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Blue', 'times_bought' => 46, 'release_date' => '2025-02-20' ],
            [ 'item_name' => 'WOMEN Tank tops White Casual and Cozy Wool and Polyester', 'price' => 54.58, 'description' => 'WOMEN Tank tops White Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 8, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'White', 'times_bought' => 19, 'release_date' => '2025-02-06' ],
            [ 'item_name' => 'KIDS Polo shirts Green Formal and Cozy Cotton and Wool', 'price' => 44.04, 'description' => 'KIDS Polo shirts Green Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 9, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'Green', 'times_bought' => 20, 'release_date' => '2025-03-30' ],
            [ 'item_name' => 'MEN Sport Yellow Formal and Cozy Cotton and Polyester', 'price' => 62.95, 'description' => 'MEN Sport Yellow Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 10, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Yellow', 'times_bought' => 5, 'release_date' => '2025-03-24' ],
            [ 'item_name' => 'WOMEN Jeans Black Formal and Cozy Wool and Polyester', 'price' => 19.16, 'description' => 'WOMEN Jeans Black Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 11, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'Black', 'times_bought' => 35, 'release_date' => '2025-02-28' ],
            [ 'item_name' => 'KIDS Shorts Black Casual and Formal Cotton and Wool', 'price' => 30.84, 'description' => 'KIDS Shorts Black Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 12, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Black', 'times_bought' => 47, 'release_date' => '2025-04-18' ],
            [ 'item_name' => 'MEN Cargo pants White Casual and Formal Cotton and Polyester', 'price' => 64.89, 'description' => 'MEN Cargo pants White Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 13, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'White', 'times_bought' => 32, 'release_date' => '2025-03-03' ],
            [ 'item_name' => 'WOMEN Tracksuit pants Yellow Casual and Formal Wool and Polyester', 'price' => 30.92, 'description' => 'WOMEN Tracksuit pants Yellow Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 14, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Yellow', 'times_bought' => 34, 'release_date' => '2025-04-20' ],
            [ 'item_name' => 'KIDS Fabric pants Yellow Casual and Cozy Cotton and Wool', 'price' => 25.71, 'description' => 'KIDS Fabric pants Yellow Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 15, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Yellow', 'times_bought' => 40, 'release_date' => '2025-03-25' ],
            [ 'item_name' => 'MEN Other White Casual and Cozy Cotton and Polyester', 'price' => 59.46, 'description' => 'MEN Other White Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 16, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'White', 'times_bought' => 47, 'release_date' => '2025-04-03' ],
            [ 'item_name' => 'WOMEN Sneakers Red Casual and Cozy Wool and Polyester', 'price' => 57.04, 'description' => 'WOMEN Sneakers Red Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 1, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Red', 'times_bought' => 15, 'release_date' => '2025-04-02' ],
            [ 'item_name' => 'KIDS Boots White Formal and Cozy Cotton and Wool', 'price' => 17.99, 'description' => 'KIDS Boots White Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 2, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'White', 'times_bought' => 2, 'release_date' => '2025-04-22' ],
            [ 'item_name' => 'MEN Sports shoes Green Formal and Cozy Cotton and Polyester', 'price' => 27.22, 'description' => 'MEN Sports shoes Green Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 3, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Green', 'times_bought' => 40, 'release_date' => '2025-02-10' ],
            [ 'item_name' => 'WOMEN Open shoes Green Formal and Cozy Wool and Polyester', 'price' => 38.73, 'description' => 'WOMEN Open shoes Green Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 4, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'Green', 'times_bought' => 30, 'release_date' => '2025-03-01' ],
            [ 'item_name' => 'KIDS Exclusive Black Casual and Formal Cotton and Wool', 'price' => 49.98, 'description' => 'KIDS Exclusive Black Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 5, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Black', 'times_bought' => 11, 'release_date' => '2025-04-09' ],
            [ 'item_name' => 'MEN Long sleeved Yellow Casual and Formal Cotton and Polyester', 'price' => 42.74, 'description' => 'MEN Long sleeved Yellow Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 6, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Yellow', 'times_bought' => 5, 'release_date' => '2025-03-03' ],
            [ 'item_name' => 'WOMEN Short sleeved Blue Casual and Formal Wool and Polyester', 'price' => 29.2, 'description' => 'WOMEN Short sleeved Blue Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 7, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Blue', 'times_bought' => 43, 'release_date' => '2025-03-21' ],
            [ 'item_name' => 'KIDS Tank tops Green Casual and Cozy Cotton and Wool', 'price' => 15.9, 'description' => 'KIDS Tank tops Green Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 8, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Green', 'times_bought' => 30, 'release_date' => '2025-02-22' ],
            [ 'item_name' => 'MEN Polo shirts Black Casual and Cozy Cotton and Polyester', 'price' => 63.25, 'description' => 'MEN Polo shirts Black Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 9, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Black', 'times_bought' => 2, 'release_date' => '2025-04-22' ],
            [ 'item_name' => 'WOMEN Sport Blue Casual and Cozy Wool and Polyester', 'price' => 37.84, 'description' => 'WOMEN Sport Blue Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 10, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Blue', 'times_bought' => 6, 'release_date' => '2025-02-03' ],
            [ 'item_name' => 'KIDS Jeans Blue Formal and Cozy Cotton and Wool', 'price' => 49.58, 'description' => 'KIDS Jeans Blue Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 11, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'Blue', 'times_bought' => 16, 'release_date' => '2025-04-09' ],
            [ 'item_name' => 'MEN Shorts Black Formal and Cozy Cotton and Polyester', 'price' => 69.52, 'description' => 'MEN Shorts Black Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 12, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Black', 'times_bought' => 47, 'release_date' => '2025-02-22' ],
            [ 'item_name' => 'WOMEN Cargo pants White Formal and Cozy Wool and Polyester', 'price' => 48.7, 'description' => 'WOMEN Cargo pants White Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 13, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'White', 'times_bought' => 27, 'release_date' => '2025-02-23' ],
            [ 'item_name' => 'KIDS Tracksuit pants Black Casual and Formal Cotton and Wool', 'price' => 48.37, 'description' => 'KIDS Tracksuit pants Black Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 14, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Black', 'times_bought' => 28, 'release_date' => '2025-04-16' ],
            [ 'item_name' => 'MEN Fabric pants Black Casual and Formal Cotton and Polyester', 'price' => 23.4, 'description' => 'MEN Fabric pants Black Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 15, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Black', 'times_bought' => 34, 'release_date' => '2025-03-26' ],
            [ 'item_name' => 'WOMEN Other Green Casual and Formal Wool and Polyester', 'price' => 32.31, 'description' => 'WOMEN Other Red Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 16, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Red', 'times_bought' => 28, 'release_date' => '2025-03-28' ],
            [ 'item_name' => 'KIDS Sneakers Blue Casual and Cozy Cotton and Wool', 'price' => 69.47, 'description' => 'KIDS Sneakers Blue Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 1, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Blue', 'times_bought' => 13, 'release_date' => '2025-04-05' ],
            [ 'item_name' => 'MEN Boots Black Casual and Cozy Cotton and Polyester', 'price' => 44.13, 'description' => 'MEN Boots Black Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 2, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Black', 'times_bought' => 24, 'release_date' => '2025-04-21' ],
            [ 'item_name' => 'WOMEN Sports shoes Blue Casual and Cozy Wool and Polyester', 'price' => 61.13, 'description' => 'WOMEN Sports shoes Blue Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 3, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Blue', 'times_bought' => 18, 'release_date' => '2025-03-24' ],
            [ 'item_name' => 'KIDS Open shoes White Formal and Cozy Cotton and Wool', 'price' => 15.06, 'description' => 'KIDS Open shoes White Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 4, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'White', 'times_bought' => 48, 'release_date' => '2025-04-17' ],
            [ 'item_name' => 'MEN Exclusive Blue Formal and Cozy Cotton and Polyester', 'price' => 50.2, 'description' => 'MEN Exclusive Blue Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 5, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Blue', 'times_bought' => 6, 'release_date' => '2025-02-08' ],
            [ 'item_name' => 'WOMEN Long sleeved White Formal and Cozy Wool and Polyester', 'price' => 22.2, 'description' => 'WOMEN Long sleeved White Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 6, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'White', 'times_bought' => 20, 'release_date' => '2025-03-26' ],
            [ 'item_name' => 'KIDS Short sleeved Yellow Casual and Formal Cotton and Wool', 'price' => 37.79, 'description' => 'KIDS Short sleeved Yellow Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 7, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Yellow', 'times_bought' => 21, 'release_date' => '2025-04-21' ],
            [ 'item_name' => 'MEN Tank tops Green Casual and Formal Cotton and Polyester', 'price' => 65.38, 'description' => 'MEN Tank tops Green Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 8, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Green', 'times_bought' => 2, 'release_date' => '2025-03-08' ],
            [ 'item_name' => 'WOMEN Polo shirts Blue Casual and Formal Wool and Polyester', 'price' => 63.76, 'description' => 'WOMEN Polo shirts Blue Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 9, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Blue', 'times_bought' => 40, 'release_date' => '2025-04-02' ],
            [ 'item_name' => 'KIDS Sport Red Casual and Cozy Cotton and Wool', 'price' => 16.31, 'description' => 'KIDS Sport Red Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 10, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Red', 'times_bought' => 48, 'release_date' => '2025-03-06' ],
            [ 'item_name' => 'MEN Jeans Yellow Casual and Cozy Cotton and Polyester', 'price' => 16.63, 'description' => 'MEN Jeans Yellow Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 11, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Yellow', 'times_bought' => 45, 'release_date' => '2025-02-06' ],
            [ 'item_name' => 'WOMEN Shorts White Casual and Cozy Wool and Polyester', 'price' => 32.88, 'description' => 'WOMEN Shorts White Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 12, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'White', 'times_bought' => 43, 'release_date' => '2025-02-21' ],
            [ 'item_name' => 'KIDS Cargo pants Blue Formal and Cozy Cotton and Wool', 'price' => 38.22, 'description' => 'KIDS Cargo pants Blue Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 13, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'Blue', 'times_bought' => 29, 'release_date' => '2025-03-31' ],
            [ 'item_name' => 'MEN Tracksuit pants Green Formal and Cozy Cotton and Polyester', 'price' => 35.39, 'description' => 'MEN Tracksuit pants Green Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 14, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Green', 'times_bought' => 12, 'release_date' => '2025-04-26' ],
            [ 'item_name' => 'WOMEN Fabric pants White Formal and Cozy Wool and Polyester', 'price' => 23.5, 'description' => 'WOMEN Fabric pants White Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 15, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'White', 'times_bought' => 36, 'release_date' => '2025-03-09' ],
            [ 'item_name' => 'KIDS Other Red Casual and Formal Cotton and Wool', 'price' => 33.57, 'description' => 'KIDS Other Red Casual and Formal Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 16, 'main_category' => 'KIDS', 'style_fabric' => 27, 'colour' => 'Red', 'times_bought' => 14, 'release_date' => '2025-04-22' ],
            [ 'item_name' => 'MEN Sneakers Blue Casual and Formal Cotton and Polyester', 'price' => 51.82, 'description' => 'MEN Sneakers Blue Casual and Formal Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 1, 'main_category' => 'MEN', 'style_fabric' => 43, 'colour' => 'Blue', 'times_bought' => 48, 'release_date' => '2025-03-17' ],
            [ 'item_name' => 'WOMEN Boots Red Casual and Formal Wool and Polyester', 'price' => 24.83, 'description' => 'WOMEN Boots Red Casual and Formal Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 2, 'main_category' => 'WOMEN', 'style_fabric' => 51, 'colour' => 'Red', 'times_bought' => 18, 'release_date' => '2025-04-29' ],
            [ 'item_name' => 'KIDS Sports shoes Yellow Casual and Cozy Cotton and Wool', 'price' => 52.49, 'description' => 'KIDS Sports shoes Yellow Casual and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 3, 'main_category' => 'KIDS', 'style_fabric' => 29, 'colour' => 'Yellow', 'times_bought' => 7, 'release_date' => '2025-02-16' ],
            [ 'item_name' => 'MEN Open shoes Black Casual and Cozy Cotton and Polyester', 'price' => 62.81, 'description' => 'MEN Open shoes Black Casual and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 4, 'main_category' => 'MEN', 'style_fabric' => 45, 'colour' => 'Black', 'times_bought' => 24, 'release_date' => '2025-04-19' ],
            [ 'item_name' => 'WOMEN Exclusive Black Casual and Cozy Wool and Polyester', 'price' => 44.7, 'description' => 'WOMEN Exclusive Black Casual and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 5, 'main_category' => 'WOMEN', 'style_fabric' => 53, 'colour' => 'Black', 'times_bought' => 34, 'release_date' => '2025-04-08' ],
            [ 'item_name' => 'KIDS Long sleeved White Formal and Cozy Cotton and Wool', 'price' => 37.15, 'description' => 'KIDS Long sleeved White Formal and Cozy Cotton and Wool perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for kids who value comfort and design.', 'category_id' => 6, 'main_category' => 'KIDS', 'style_fabric' => 30, 'colour' => 'White', 'times_bought' => 3, 'release_date' => '2025-02-11' ],
            [ 'item_name' => 'MEN Short sleeved Red Formal and Cozy Cotton and Polyester', 'price' => 19.9, 'description' => 'MEN Short sleeved Red Formal and Cozy Cotton and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for men who value comfort and design.', 'category_id' => 7, 'main_category' => 'MEN', 'style_fabric' => 46, 'colour' => 'Red', 'times_bought' => 35, 'release_date' => '2025-02-19' ],
            [ 'item_name' => 'WOMEN Tank tops White Formal and Cozy Wool and Polyester', 'price' => 33.74, 'description' => 'WOMEN Tank tops White Formal and Cozy Wool and Polyester perfect for modern wardrobes.', 'parameters' => 'A fashionable choice for women who value comfort and design.', 'category_id' => 8, 'main_category' => 'WOMEN', 'style_fabric' => 54, 'colour' => 'White', 'times_bought' => 46, 'release_date' => '2025-03-31' ]
        ]);
    }
}
